
export const AdminPath = {
    DASHBOARD: "",
    ORDERS: "orders",
    PRODUCTS: "products",
    PRODUCT_LIST:"product-list",
    PRODUCT_CATEGORY: "product-category",
    PRODUCT_COLOR: "product-color",
    PRODUCT_BRAND: "product-brand",
    PRODUCT_SIZE: "product-size",
    BLOGS: "blogs",
    BLOG_LIST: 'blog-list',
    BLOG_CATEGORY: "blog-category",
    REPORTS: "reports",
    CUSTOMERS: "customers"
}

export const Query = {
    ASC : "ASC",
    DESC: "DESC",
}
// status for API fetching
export const Status = {
    IDLE: "idle",
    LOADING: "loading",
    SUCCEEDED: "succeed",
    FAILED: "failed"
}
export const ORDER_STATUS = {
    ORDERING: "ordering",
    ORDERED: "ordered",
    DELIVERY: "delivery",
    COMPLETED: "completed",
    CANCELED: "canceled"
}
export const ACTION = {
    /****************** ADMIN ACTION*********************/
    //------------------BLOG ACTION----------------------------
    //Error Action
    ERROR: "ERROR",

    //Blog Category Action
    GET_BLOG_CATEGORIES: "GET_BLOG_CATEGORIES",
    CREATE_BLOG_CATEGORY: "CREATE_BLOG_CATEGORY",
    UPDATE_BLOG_CATEGORY: "UPDATE_BLOG_CATEGORY",
    DELETE_BLOG_CATEGORY: "DELETE_BLOG_CATEGORY",
    IS_DELETING_BLOG_CATEGORY: "IS_DELETING_BLOG_CATEGORY",
    BLOG_CATEGORY_STATUS: "BLOG_CATEGORY_STATUS",

     //Blog Action
    GET_BLOGS: "GET_BLOGS",
    GET_BLOG_BY_ID: "GET_BLOG_BY_ID",
    INIT_BLOG:"INIT_BLOG",
    CREATE_BLOG: "CREATE_BLOG",
    UPDATE_BLOG: "UPDATE_BLOG",
    DELETE_BLOG: "DELETE_BLOG",
    IS_DELETING_BLOG: "IS_DELETING_BLOG",
    BLOG_STATUS: "BLOG_STATUS",

    //------------------PRODUCT ACTION----------------------------
    //Product Size Action
    GET_PRODUCT_SIZES: "GET_PRODUCT_SIZES",
    CREATE_PRODUCT_SIZE: "CREATE_PRODUCT_SIZE",
    UPDATE_PRODUCT_SIZE: "UPDATE_PRODUCT_SIZE",
    DELETE_PRODUCT_SIZE: "DELETE_PRODUCT_SIZE",
    IS_DELETING_PRODUCT_SIZE: "IS_DELETING_PRODUCT_SIZE",
    PRODUCT_CATEGORY_STATUS: "PRODUCT_CATEGORY_STATUS",

     //Product Color Action
     GET_PRODUCT_COLORS: "GET_PRODUCT_COLORS",
     CREATE_PRODUCT_COLOR: "CREATE_PRODUCT_COLOR",
     UPDATE_PRODUCT_COLOR: "UPDATE_PRODUCT_COLOR",
     DELETE_PRODUCT_COLOR: "DELETE_PRODUCT_COLOR",
     IS_DELETING_PRODUCT_COLOR: "IS_DELETING_PRODUCT_COLOR",
     PRODUCT_COLOR_STATUS: "  PRODUCT_COLOR_STATUS",

      //Product  Brand Action
    GET_PRODUCT_BRANDS: "GET_PRODUCT_BRANDS",
    CREATE_PRODUCT_BRAND: "CREATE_PRODUCT_BRAND",
    UPDATE_PRODUCT_BRAND: "UPDATE_PRODUCT_BRAND",
    DELETE_PRODUCT_BRAND: "DELETE_PRODUCT_BRAND",
    IS_DELETING_PRODUCT_BRAND: "IS_DELETING_PRODUCT_BRAND",
    PRODUCT_BRAND_STATUS : "  PRODUCT_BRAND_STATUS", 

    //Product Category Action
    GET_PRODUCT_CATEGORIES: "GET_PRODUCT_CATEGORIES",
    CREATE_PRODUCT_CATEGORY: "CREATE_PRODUCT_CATEGORY",
    UPDATE_PRODUCT_CATEGORY: "UPDATE_PRODUCT_CATEGORY",
    DELETE_PRODUCT_CATEGORY: "DELETE_PRODUCT_CATEGORY",
    IS_DELETING_PRODUCT_CATEGORY: "IS_DELETING_PRODUCT_CATEGORY",
    PRODUCT_CATEGORY_STATUS: "PRODUCT_CATEGORY_STATUS",

    //Product Action
    GET_PRODUCTS: "GET_PRODUCT_PRODUCTS",
    GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    IS_DELETING_PRODUCT: "IS_DELETING",
    PRODUCT_STATUS: "PRODUCT_STATUS",
    
    //Product Action
    CREATE_PRODUCT_VARIANT: "CREATE_PRODUCT_VARIANT",
    UPDATE_PRODUCT_VARIANT: "UPDATE_PRODUCT_VARIANT",
    DELETE_PRODUCT_VARIANT: "DELETE_PRODUCT_VARIANT",
    IS_DELETING_PRODUCT_VARIANT: "IS_DELETING_PRODUCT_VARIANT",
    PRODUCT_VARIANT_STATUS: "PRODUCT_VARIANT_STATUS",

    //------------------USER ACTION----------------------------
    //User Action
    GET_USERS: "GET_USER",
    GET_USER_BY_ID: "GET_USER_BY_ID",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    USER_STATUS: "USER_STATUS",
    USER_MESSAGE: "USEr_MESSAGE",

    //Auth Action
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    AUTH_STATUS: "AUTH_STATUS",

    //------------------ORDER ACTION----------------------------
    //Order Action
    GET_ORDERS: "GET_ORDERS",
    GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
    UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
    DELETE_ORDER: "DELETE_ORDER",
    ORDER_STATUS: "ORDER_STATUS",
    /****************** GUEST ACTION*********************/
    //Home Action:
    BLOG_CATEGORIES: "BLOG_CATEGORIES",
    BLOG: "BLOG",
    BLOG_LIST: "BLOG_LIST",
    PRODUCT_CATEGORIES: "PRODUCT_CATEGORIES",
    PRODUCT_BRANDS: "PRODUCT_BRANDS",
    PRODUCT_LIST:"PRODUCT_LIST",
    PRODUCT: "PRODUCT",
    NEW_ARRIVALS: "GET_NEW_ARRIVALS",
    LATEST_BLOGS: "GET_LATEST_BLOGS",

    //Order Action:
    ADD_ITEM: "ADD_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    UPDATE_ITEM_QUANTITY: "UPDATE_ITEM_QUANTY",

    //Authorization Action 
    AUTH: "AUTH",
    LOGOUT: "LOGOUT",
    AUTH_LOADING: "AUTH_LOADING",
    AUTH_ERROR: "AUTH_ERROR",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    USER_ORDERS: "USER_ORDERS",
    GET_ORDER_AFTER_LOGIN: "GET_ORDER_AFTER_LOGIN",
    UPDATE_ORDER: "UPDATE_ORDER",



   





}