


export const AdminPath = {
    DASHBOARD: "dashboard",
    ORDERS: "orders",
    PRODUCTS: "products",
    BLOGS: "blogs",
    REPORTS: "reports",
    CUSTOMERS: "customers"
}

export const Query = {
    ASC : "ASC",
    DESC: "DESC",
}

export const ACTION = {
    ERROR: "ERROR",
    GET_BLOG_CATEGORIES: "GET_BLOG_CATEGORIES",
    CREATE_BLOG_CATEGORY: "CREATE_BLOG_CATEGORY",
    UPDATE_BLOG_CATEGORY: "UPDATE_BLOG_CATEGORY",
    DELETE_BLOG_CATEGORY: "DELETE_BLOG_CATEGORY",
    IS_DELETING_BLOG_CATEGORY: "IS_DELETING_BLOG_CATEGORY",

    GET_BLOGS: "GET_BLOGS",
    GET_BLOG_BY_ID: "GET_BLOG_BY_ID",
    INIT_BLOG:"INIT_BLOG",
    CREATE_BLOG: "CREATE_BLOG",
    UPDATE_BLOG: "UPDATE_BLOG",
    DELETE_BLOG: "DELETE_BLOG",
    IS_DELETING_BLOG: "IS_DELETING_BOG"

}